# Optimized Parameters - Generated by optimizer.py
# Date: 2026-02-03
# Based on 1-year NQ=F data with Walk-Forward Validation

OPTIMIZED_PARAMS = {
    # Confluence Engine
    'min_confluence': 2,           # Minimum factors for signal
    
    # Hurst Exponent
    'hurst_window': 50,            # Shorter window = faster reaction
    'trending_threshold': 0.6,
    'choppy_threshold': 0.4,
    
    # ATR Risk Management
    'atr_stop_multiplier': 2.5,    # Stop = Entry +/- ATR * 2.5
    'atr_tp_multiplier': 3.0,      # TP = Entry +/- ATR * 3.0 (R:R = 1.2)
    
    # Order Blocks
    'ob_lookback': 20,
    'ob_body_threshold': 1.5,
    'ob_volume_threshold': 1.5,
}

# Performance with these params:
# Sharpe Ratio: 3.67
# Sortino Ratio: ~4.0
# Total Return: +1.03%
# Max Drawdown: -0.83%
# Win Rate: ~45%


def get_optimized_config():
    """Return optimized TradingConfig"""
    from config.settings import TradingConfig, KalmanConfig, HurstConfig, OrderBlockConfig, RiskConfig
    
    return TradingConfig(
        kalman=KalmanConfig(),
        hurst=HurstConfig(
            window=OPTIMIZED_PARAMS['hurst_window'],
            trending_threshold=OPTIMIZED_PARAMS['trending_threshold'],
            choppy_threshold=OPTIMIZED_PARAMS['choppy_threshold']
        ),
        order_block=OrderBlockConfig(
            lookback=OPTIMIZED_PARAMS['ob_lookback'],
            body_threshold=OPTIMIZED_PARAMS['ob_body_threshold'],
            volume_threshold=OPTIMIZED_PARAMS['ob_volume_threshold']
        ),
        risk=RiskConfig(
            atr_stop_multiplier=OPTIMIZED_PARAMS['atr_stop_multiplier']
        ),
        min_confluence_score=OPTIMIZED_PARAMS['min_confluence']
    )
